### ISSUE TITLE
Make package PEP 561 compliant

### ISSUE THREAD

**Issue by stansotn** [citrusvanilla/tinyflux#30]
### Functionality to improve and goal

Though `tinyflux` codebase  is widely type annotated, the type annotations supplied with the `tinyflux` package are not used during static analysis (i.e. `mypy`) when imported as a dependency in other projects.

Specifically, this causes `mypy` to output the following error and render any class imported from `tinyflux` package as imprecise.

```
error: Skipping analyzing "tinyflux": module is installed, but missing library stubs or py.typed marker  [import]
```

### Proposal

Add `py.typed` file at the root of the package directory. 

### Links and references

[PEP 561](https://peps.python.org/pep-0561/)

**Comment by citrusvanilla** [comment]
thanks @stansotn for the clean PR and supporting information.  this branch was merged into master and tinyflux is pep 561 compliant with the v0.2.6 release.
