### ISSUE TITLE
Documentation typos, taking `tinydb` as `tinyflux`

### ISSUE THREAD

**Issue by James4Ever0** [citrusvanilla/tinyflux#48]
**Describe the bug**
Some documentation pages of this project have errors in example code snippets, and more accurately `tinydb` is used instead of `tinyflux`. You can search for all occurances [here](https://tinyflux.readthedocs.io/en/latest/search.html?q=from+tinydb+import&check_keywords=yes&area=default).

**To Reproduce**
1. Go to [this page](https://tinyflux.readthedocs.io/en/latest/querying-data.html)
2. Search for `from tinydb import`
3. Scroll down the page

**Expected behavior**
`tinyflux` shall be used instead.

**Screenshots**
<img width="799" alt="image" src="https://github.com/citrusvanilla/tinyflux/assets/103997068/c42584df-8c30-48cc-bbc9-b5e372a8a7d7">

**Additional context**
Someone has made a [pull request](https://github.com/citrusvanilla/tinyflux/pull/47) for this issue.

**Comment by elliotfontaine** [comment]
The code review for this PR is trivial @citrusvanilla

**Comment by citrusvanilla** [comment]
thanks @James4Ever0 and @elliotfontaine this has been fixed on main.

**Comment by citrusvanilla** [comment]
completed by @Tejasweee
